### ISSUE TITLE
Edit Profile does not work on web for College XYZ

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#443]
collegexyz@mailinator.com
Volleyball11$

**Comment by technicalbirdVayuz** [comment]
Fixed

**Comment by stevekamps** [comment]
not fixed.  see video

https://user-images.githubusercontent.com/77851393/151020217-cb85fc0b-0a8f-462d-9e23-869543f64b5b.mp4

**Comment by rgnarok** [comment]
Not working

**Comment by technicalbirdVayuz** [comment]
Fixed, I worked on Edit form previously, there was also 1 issue

**Comment by stevekamps** [comment]
works. closing
