### ISSUE TITLE
Dashboard - Events creation 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#594]
VU Admin from dashbaord cannot create an event for all users to see in the feed.  When I create an event it makes the feed screen go grey on the app for users.

**Comment by stevekamps** [comment]
when is this going to be fixed?

**Comment by ShikharVayuz** [comment]
https://vayuztechnologies-my.sharepoint.com/:v:/g/personal/shikhar_jain_vayuztechnologies_onmicrosoft_com/ESiXTCSMMm5CvhFGTzVV1N0B-66P5AbfufoSGthNIkOoVg?e=erDUbu

**Comment by stevekamps** [comment]
I was referring to VU admin creating events in the dashboard area

**Comment by ShikharVayuz** [comment]
@stevekamps I have just created an public event from admin its working fine.

**Comment by ShikharVayuz** [comment]
https://vayuztechnologies-my.sharepoint.com/:v:/g/personal/shikhar_jain_vayuztechnologies_onmicrosoft_com/EX9SQb08cthHq8MOQp9h1VcBGJjYjMm5cEWSkIAFYaCj0w

**Comment by ShikharVayuz** [comment]
https://vayuztechnologies-my.sharepoint.com/:v:/g/personal/shikhar_jain_vayuztechnologies_onmicrosoft_com/EX9SQb08cthHq8MOQp9h1VcBGJjYjMm5cEWSkIAFYaCj0w

**Comment by stevekamps** [comment]
![Screenshot 2022-04-08 at 9 35 49 AM](https://user-images.githubusercontent.com/77851393/162475802-4ac7b641-11df-4a16-9248-29163a8966af.png)

**Comment by stevekamps** [comment]
Please fix the issue with the html letters showing up

**Comment by stevekamps** [comment]
https://user-images.githubusercontent.com/77851393/162475868-70248c4f-196e-4b7f-abe5-4f209b2e4e96.MP4

**Comment by ShikharVayuz** [comment]
Fixed : version : 1.0.6

**Comment by stevekamps** [comment]
Not fixed.  Still same issues with the html letters and the blank screen when I try to open the event

**Comment by stevekamps** [comment]
https://user-images.githubusercontent.com/77851393/162998359-7cc6eb4e-7f9a-468b-808a-e25453d204d9.MP4

**Comment by stevekamps** [comment]
Still not fixed on version 1.0.6.  Events have the <p> stuff in the text and when a user click on it on the app the screen goes grey

**Comment by ShikharVayuz** [comment]
@stevekamps  Please check this issue now ios build was updated on this monday for the same.

**Comment by stevekamps** [comment]
No this is not working on version 1.0.6. 
The HTML code is still seen in the description and when I click on event it goes to a grey screen

**Comment by stevekamps** [comment]
https://user-images.githubusercontent.com/77851393/164042974-973a7543-71c0-4eeb-b89d-98f7aaa7f46f.MP4

**Comment by ShikharVayuz** [comment]
It's working fine steve
![Uploading Screenshot_20220419-222350.png…]()

**Comment by ShikharVayuz** [comment]
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/86296418/164056317-f935c1b0-402f-4160-b8ba-d8d184732194.png)
steve its working fine.

**Comment by stevekamps** [comment]
Not working fine on mine or Ryan's App.

**Comment by stevekamps** [comment]
My screenshot video was from 1 hour ago.  Version 1.0.6

**Comment by stevekamps** [comment]
Not working on Version 1.0.2 (6) which as just moved to the appstore.  Still same HTML code showing and when we click on event it goes to get screen. See attached video

https://user-images.githubusercontent.com/77851393/164290285-eb5c5f11-9b0e-447e-a1fd-6138b7d5db58.MP4

**Comment by rohitrvayuz** [comment]
![Simulator Screen Shot - iPhone 13 - 2022-04-21 at 10 06 09](https://user-images.githubusercontent.com/78350161/164373095-638731a5-9642-4063-8f20-ae4ce391cbe3.png)
iOS
